# image: registry.erda.cloud/erda/terminus-nodejs:node.12.8.1.npm.6.10.2

FROM registry.erda.cloud/erda/terminus-centos:base

LABEL maintainer="lj@terminus.io"

ENV SASS_BINARY_SITE="https://npm.taobao.org/mirrors/node-sass"
ENV NODEJS_ORG_MIRROR="https://npm.taobao.org/dist"

ENV LC_ALL=en_US.utf8

RUN yum install -y git openssh curl

ENV NODE_VERSION 12.8.1

# nodejs
RUN \
    curl --silent --location https://rpm.nodesource.com/setup_12.x | bash - && \
    yum install -y nodejs-$NODE_VERSION

RUN npm config set @terminus:registry http://registry.npm.terminus.io/ && \
    npm config set registry http://registry.npm.taobao.org/
