# image: registry.erda.cloud/erda/terminus-nodejs:12.13

FROM registry.erda.cloud/erda/terminus-centos:base

LABEL maintainer="lj@terminus.io"

ENV SASS_BINARY_SITE="https://npm.taobao.org/mirrors/node-sass"
ENV NODEJS_ORG_MIRROR="https://npm.taobao.org/dist"

ENV LC_ALL=en_US.utf8

RUN yum install -y git openssh curl gcc make bzip2 gcc-c++

ENV NODE_VERSION 12.13.1

# nodejs
RUN \
    curl --silent --location https://rpm.nodesource.com/setup_12.x | bash - && \
    yum install -y nodejs-$NODE_VERSION

RUN npm config set @terminus:registry https://registry.npm.terminus.io/ && \
    npm config set registry https://registry.npm.taobao.org/
