# image: registry.erda.cloud/erda/terminus-nodejs:12.13

FROM registry.erda.cloud/erda/terminus-centos:base

LABEL maintainer="lj@terminus.io"

ENV SASS_BINARY_SITE="https://npmmirror.com/mirrors/node-sass"
ENV NODEJS_ORG_MIRROR="https://npmmirror.com/dist"

ENV LC_ALL=en_US.utf8

RUN yum install -y openssh curl gcc make bzip2 gcc-c++

ENV NODE_VERSION 12.13.1

# nodejs
RUN \
    curl --silent --location https://rpm.nodesource.com/setup_12.x | bash - && \
    yum install -y nodejs-$NODE_VERSION

RUN npm config set @terminus:registry https://registry.npm.terminus.io/ && \
    npm config set registry https://registry.npmmirror.com/

# git 2.24.4
RUN yum install -y \
https://repo.ius.io/ius-release-el7.rpm \
https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum install -y git224
