### job 配置项
jobs:
  java:
    image: registry.erda.cloud/erda-actions/java-action:20210803-e4add7b
    envs:
      # 详见 actions/buildpack/1.0/dice.yml
      BP_DOCKER_BASE_REGISTRY: registry.erda.cloud
    resources:
      cpu: 0.5
      mem: 2048
      disk: 1024
#  预留，pipeline级别实现全局缓存
#  binds:
#    - ((storageMountPoint))/devops/storage/pipeline_build_cache:/opt/build_cache
