### job 配置项
jobs:
  agent:
    image: registry.erda.cloud/erda-actions/action-agent:2.3-alpha-20220805091812-fd603193b
    labels:
      # 必填字段
      MD5: 9c97f21ba03ed164529a0d9969ac7cc6
    envs:
      # DEBUG mode, will produce more logs
      DEBUG: false
      # push log to collector
      ENABLE_PUSH_LOG_TO_COLLECTOR: false
      STDERR_REGEXP_LIST: '["^[a-z]*can*","^[a-z]*fail*"]'
      ENCRYPTED_VAlUE_MIN_LEN: 6
      FILE_STREAM_TIMEOUT_SEC: 60
      DEFAULT_SHELL: sh -x -e
