# Git: git version 2.30.2
# gcc: 10.2.1 20210110
# Node: 14.17.5 LTS, npm: 6.14.14, yarn: 1.22.5
# /etc/os-release: Debian: Debian GNU/Linux 11 (bullseye)
# Kernel(uname -a): Linux 08f4f27793e7 5.10.47-linuxkit Sat Jul 3 21:51:47 2021 x86_64
# Build cmd: docker build . -t terminus/debian-node-14.17 -f Dockerfile.debian.npm.6.14
# Other tags: terminus/debian-node:14.17-lts,terminus/debian-node:14.17
FROM node:14.17.5-bullseye-slim

LABEL maintainer=hustcer<majun@terminus.io>

# Use mirrors to speed up installation
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak \
    && apt update \
    && apt upgrade -y \
    && apt install apt-transport-https ca-certificates locales -y --no-install-recommends --no-install-suggests \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && echo 'deb https://mirrors.aliyun.com/debian/ bullseye main contrib non-free' > /etc/apt/sources.list \
    && echo 'deb https://mirrors.aliyun.com/debian/ bullseye-updates main contrib non-free' >> /etc/apt/sources.list \
    && echo 'deb https://mirrors.aliyun.com/debian/ bullseye-backports main contrib non-free' >> /etc/apt/sources.list \
    && echo 'deb https://mirrors.aliyun.com/debian-security bullseye-security main contrib non-free' >> /etc/apt/sources.list

ENV LANG=en_US.UTF-8
ENV NODEJS_ORG_MIRROR="https://npm.taobao.org/dist"
ENV SASS_BINARY_SITE="https://npm.taobao.org/mirrors/node-sass"

RUN npm config set @terminus:registry https://registry.npm.terminus.io/  \
    && npm config set registry https://registry.npm.taobao.org/ \
    && apt update \
    && apt install -y --no-install-recommends --no-install-suggests \
       git curl wget bzip2 unzip openssh-client gcc make g++ \
    # fnm --- Reserved expansion point:
    # See: https://github.com/Schniz/fnm, Fast and simple Node version manager
    # Make it easier and faster to switch to other node versions in the future
    # Just do: fnm install 16 && fnm use 16, will finish in 10 seconds.
    && curl -fsSL https://fnm.vercel.app/install | bash \
    # Fix: fnm can't infer your shell based on the process tree.
    && sed -i 's/fnm env/fnm env --shell=bash/' /root/.bashrc \
    && rm -rf /var/lib/apt/lists/* && apt autoremove -y \
    # Make /bin/sh symlink to bash instead of dash:
    && echo "dash dash/sh boolean false" | debconf-set-selections \
    && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
